/* OpenAPI spec version: 0.1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * modified by S. Riha (2017)
 */

package swaggerbe

import (
	"encoding/json"
	"log"
	mj "mystuff/elephancy/json"
	"net/http"
)

type Default struct {
}

func FindPageById(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	// println("*************** Finding page by ID *****************")
	w.WriteHeader(http.StatusOK)
}

func ListPages(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	http.ServeFile(w, r, "./json/pages.json")
}

func FindPageByPrettyURL(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	filename := "/home/stefan/programs/go/src/mystuff/elephancy/json/pages.json"
	pcoll, err := mj.LoadJSONnew(filename)
	if err != nil {
		log.Fatal(err)
	}
	v := r.URL.Query()
	page, err := pcoll.PrettyURLToPage(v.Get("prettyurl"))
	if err != nil {
		// println("notfound*****************************")
		http.NotFound(w, r)
	}
	json.NewEncoder(w).Encode(page)
}
