language: go
go:
  - master

language: node_js
node_js:
  - "node"

before_install:  
 - npm install gulp gulp-mocha gulp-util chai  
 - sudo apt-get update  
 - sudo apt-get install scala   

script: "gradle build"    
