language: go
go:
  - master

language: node_js
node_js:
  - "node"

before_install:  
 - npm install -g webpack

install:
 - cd ./frontendclient/typescript
 - npm install --save-dev typescript awesome-typescript-loader source-map-loader
 - npm install --save @types/node

script:
 - webpack   
