swagger: '2.0'
info:
  version: '0.1.0'
  title: Elephancy backend (Simple)
  description: Elephancy backend (Simple)
host: 127.0.0.1:8080
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pages:
    get:
      description: Returns all pages 
      operationId: listPages
      produces:
        - application/json
      responses:
        '200':
          description: pages response
          schema:
            type: array
            items:
              $ref: '#/definitions/page'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /pages/FindPageByKeyValue:
    get:
      description: Find page by key-value pair
      operationId: findPageByKeyValue
      produces:
        - application/json
      parameters:
        - name: key
          in: query
          description: Page property
          required: true
          type: string
        - name: value
          in: query
          description: Value of page property
          required: true
          type: string
      responses:
        '200':
          description: return page
          schema:
            $ref: '#/definitions/page'
        '404':
          description: page not found
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  page:
    type: object
    required:
      - id
      - links
      - prettyurl
      - linkname
      - linkweight
      - metatitle
    properties:
      id:
        type: integer
        format: int64
      links:
        "$ref": "#/definitions/links"
      prettyurl:
        type: string
      linkname:
        type: string
      linkweight:
        type: string
      metatitle:
        type: string
  links:
    type: array
    items:
      $ref: '#/definitions/link'
  link:
    type: object
    required:
     - rel
     - href
    properties:
      rel:
        type: string
      href:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
        