/* OpenAPI spec version: 0.1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * modified by S. Riha (2017)
 */

package api

import (
	"encoding/json"
	"io/ioutil"
	"log"
	jc "mystuff/elephancy/jsoncommon"
	"net/http"
	"strconv"
)

type Configuration struct {
	ApiAddress     string
	ApiDataFile    string
	ApiResourceDir string
}

var datafile = "../restapi/data/pages.json"
var apiRoot = "../restapi"

func LoadConfig(filename string) Configuration {
	bytearr, err := ioutil.ReadFile(filename)
	if err != nil {
		log.Fatal(err)
	}

	var c Configuration
	err = json.Unmarshal(bytearr, &c)
	if err != nil {
		log.Fatal(err)
	}
	return c
}

func ListPages(c Configuration, w http.ResponseWriter, r *http.Request) {
	w.Header().Add("Cache-Control", "no-cache")
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	http.ServeFile(w, r, c.ApiDataFile)
}

// func FindPageByPrettyURL(w http.ResponseWriter, r *http.Request) {
// 	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
// 	datafile := "/home/stefan/programs/go/src/mystuff/elephancy/json/pages.json"
// 	pages, err := jc.LoadPages(datafile)
// 	if err != nil {
// 		log.Fatal(err)
// 	}
// 	v := r.URL.Query()
// 	// page, err := pages.PrettyURLToPage(v.Get("prettyurl"))
// 	page, err := pages.GetPageByPrettyURL(v.Get("prettyurl"))
// 	if err != nil {
// 		// println("notfound*****************************")
// 		http.NotFound(w, r)
// 	}
// 	json.NewEncoder(w).Encode(page)
// }

// func FindPageByLinksSelf(w http.ResponseWriter, r *http.Request) {
// 	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
// 	datafile := "/home/stefan/programs/go/src/mystuff/elephancy/json/pages.json"
// 	pages, err := jc.LoadPages(datafile)
// 	if err != nil {
// 		log.Fatal(err)
// 	}
// 	page, err := pages.GetPageByLinksSelf(r.URL.Path)
// 	println(page.Links.Self)
// 	if err != nil {
// 		// println("notfound*****************************")
// 		http.NotFound(w, r)
// 	}
// 	json.NewEncoder(w).Encode(page)
// }

// FindPageByKeyValue finds pages based on a single key-value pair of its properties
func FindPageByKeyValue(c Configuration, w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	pages, err := jc.LoadPages(c.ApiDataFile)
	if err != nil {
		log.Fatal(err)
	}
	vals := r.URL.Query()
	var page jc.Page
	switch vals["key"][0] {
	case "prettyurl":
		page, err = pages.GetPageByPrettyURL(vals["value"][0])

	default:
		http.NotFound(w, r)
	}
	json.NewEncoder(w).Encode(page)
}

// Should be used by client-side only?
func GetPageContent(c Configuration, w http.ResponseWriter, r *http.Request) {
	ajax := r.Header.Get("myheader")
	if ajax == "XMLHttpRequest" {
		w.Header().Set("Content-Type", "text/html; charset=UTF-8")

		pages, err := jc.LoadPages(c.ApiDataFile)
		if err != nil {
			log.Fatal(err)
		}
		ids := r.URL.Path[len("/api/content/"):]
		id, err := strconv.ParseInt(ids, 0, 64)
		if err != nil || (id == 0) {
			http.NotFound(w, r)
			return
		}
		page, err := pages.GetPageById(id)
		if err != nil {
			http.NotFound(w, r)
		}

		// get the content
		hrefSelf, err := page.GetLinkByRel("self")
		if err != nil {
			log.Fatal(err)
		}
		http.ServeFile(w, r, c.ApiResourceDir+hrefSelf)
	} else {
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte("400 - Request is not an XMLHttpRequest."))
	}

}

// // FileServer serves files WITHOUT caching policy to server-side frontend
// func FileServer(c Configuration, w http.ResponseWriter, r *http.Request) {
// 	// No caching policy here. Must be handled by frontend.
// 	http.StripPrefix("/resources/", http.FileServer(http.Dir(c.ApiResourceDir))).ServeHTTP(w, r)
// }
